# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kimsunghoon_Ios_programming_week_7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kimsunghoon_Ios_programming_week_7
  pod 'Progress'
end
